### ISSUE TITLE
unable to start a new HAR file

### ISSUE THREAD

**Issue by olbrich** [webmetrics/browsermob-proxy#8]
I have been experimenting with using browsermob proxy and have done the following:

(using Mac Pro w/ Lion ...  java version "1.6.0_26" Java(TM) SE Runtime Environment (build 1.6.0_26-b03-383-11A511) Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02-383, mixed mode)

downloaded the latest binaries from https://browsermob.s3.amazonaws.com/proxy/browsermob-proxy-2.0-SNAPSHOT-bin.zip
unpacked 
run bin/browsermob-proxy

curl -i -X POST http://localhost:8080/proxy  #=> proxy: 9091
curl -i -X PUT http://localhost:8080/proxy/9091/har

As this point I get a stack trace like this....

2011-09-02 14:24:09.157:WARN::/proxy/9091/har
java.lang.RuntimeException: Sitebricks received a null reply from the resource.
    at com.google.sitebricks.headless.ReplyBasedHeadlessRenderer.render(ReplyBasedHeadlessRenderer.java:25)
    at com.google.sitebricks.routing.WidgetRoutingDispatcher.bindAndReply(WidgetRoutingDispatcher.java:90)
    at com.google.sitebricks.routing.WidgetRoutingDispatcher.dispatch(WidgetRoutingDispatcher.java:73)
    at com.google.sitebricks.DebugModeRoutingDispatcher.dispatch(DebugModeRoutingDispatcher.java:63)
    at com.google.sitebricks.SitebricksFilter.doFilter(SitebricksFilter.java:41)
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
    at com.google.sitebricks.HiddenMethodFilter.doFilter(HiddenMethodFilter.java:74)
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:474)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:935)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:404)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:870)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:346)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1068)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:807)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:220)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:520)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528)
    at java.lang.Thread.run(Thread.java:680)

The documentation suggests that this is all that should be required to start capturing data, but clearly I'm missing something or I've gotten some wires crossed somewhere.  Any ideas?

**Comment by lightbody** [comment]
Looks like you're running an old version. I'll release beta 3 today and post a note here when it's ready.

**Comment by lightbody** [comment]
OK, this should be better now. Try this out 2.0-beta-3, which you can find on our brand new "website" :)

http://opensource.webmetrics.com/browsermob-proxy/
